/* Original procedural score and sound design. No recorded or third-party audio is used. */
(function(root){
  'use strict';
  class AntAudio{
    constructor(){this.ctx=null;this.master=null;this.ambient=null;this.music=null;this.fx=null;this.scene='nest';this.step=0;this.musicTimer=null;try{this.muted=localStorage.getItem('alien-ant-audio-muted')==='1';}catch{this.muted=false;}this.last={};}
    ensure(){if(this.ctx)return this.ctx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;const x=this.ctx=new AC(),master=this.master=x.createGain();master.gain.value=this.muted?0:.32;master.connect(x.destination);this.ambient=x.createGain();this.music=x.createGain();this.fx=x.createGain();this.ambient.gain.value=.14;this.music.gain.value=.18;this.fx.gain.value=.9;this.ambient.connect(master);this.music.connect(master);this.fx.connect(master);this.startAmbient();this.musicTimer=setInterval(()=>this.musicTick(),220);return x;}
    startAmbient(){const x=this.ctx,amb=this.ambient;for(const [freq,type,gain] of [[43,'sine',.28],[65,'triangle',.1],[91,'sine',.035]]){const o=x.createOscillator(),g=x.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g).connect(amb);o.start();}const len=x.sampleRate*3,buf=x.createBuffer(1,len,x.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(.34+.3*Math.sin(i/137)+.2*Math.sin(i/613));const n=x.createBufferSource(),f=this.ambientFilter=x.createBiquadFilter(),g=x.createGain();n.buffer=buf;n.loop=true;f.type='lowpass';f.frequency.value=390;g.gain.value=.04;n.connect(f).connect(g).connect(amb);n.start();}
    unlock(){const x=this.ensure();if(x?.state==='suspended')x.resume();}
    setMuted(v){this.muted=v;try{localStorage.setItem('alien-ant-audio-muted',v?'1':'0');}catch{}if(this.master)this.master.gain.setTargetAtTime(v?0:.32,this.ctx.currentTime,.04);}
    toggle(){this.unlock();this.setMuted(!this.muted);return !this.muted;}
    setScene(scene){if(!['nest','surface','combat'].includes(scene)||scene===this.scene)return;this.scene=scene;this.step=0;if(!this.ctx)return;const now=this.ctx.currentTime;this.music.gain.setTargetAtTime(scene==='combat'?.24:.18,now,.7);this.ambientFilter.frequency.setTargetAtTime(scene==='surface'?760:scene==='combat'?540:390,now,1.2);}
    synth(freq,duration=.3,type='triangle',gain=.04,when=0,destination=this.music,slide=0){const x=this.ctx;if(!x||this.muted)return;const o=x.createOscillator(),f=x.createBiquadFilter(),g=x.createGain(),now=x.currentTime+when;o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(25,freq+slide),now+duration);f.type='lowpass';f.frequency.value=Math.min(2200,Math.max(180,freq*5));g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.018);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(f).connect(g).connect(destination);o.start(now);o.stop(now+duration+.04);}
    noiseBurst(duration=.08,gain=.025,cutoff=900,when=0){const x=this.ctx;if(!x||this.muted)return;const size=Math.max(64,Math.floor(x.sampleRate*duration)),buf=x.createBuffer(1,size,x.sampleRate),data=buf.getChannelData(0);for(let i=0;i<size;i++)data[i]=(Math.random()*2-1)*(1-i/size);const src=x.createBufferSource(),f=x.createBiquadFilter(),g=x.createGain(),now=x.currentTime+when;src.buffer=buf;f.type='bandpass';f.frequency.value=cutoff;f.Q.value=1.1;g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);src.connect(f).connect(g).connect(this.fx);src.start(now);}
    insectChirp(){const root=920+Math.random()*420;this.synth(root,.045,'sine',.012,0,this.ambient,root*.55);this.synth(root*.82,.035,'sine',.008,.055,this.ambient,root*.32);}
    musicTick(){const x=this.ctx;if(!x||x.state!=='running'||this.muted)return;const patterns={nest:[0,null,null,3,null,null,-2,null,0,null,5,null,null,3,null,null],surface:[0,null,2,4,null,7,null,4,2,null,5,null,4,null,2,null],combat:[0,0,3,0,5,3,0,-2,0,3,5,7,5,3,0,-2]},roots={nest:43.65,surface:55,combat:49};const p=patterns[this.scene],pos=this.step%p.length,note=p[pos],root=roots[this.scene];if(note!==null){const freq=root*Math.pow(2,note/12);this.synth(freq,this.scene==='combat'?.2:.52,this.scene==='combat'?'sawtooth':'triangle',this.scene==='combat'?.026:.025);if(pos%4===0)this.synth(freq*2,this.scene==='surface'?.34:.48,'sine',.013,.025);}if(pos%8===0)this.synth(root/2,1.25,'sine',.025);if(this.scene==='combat'){if(pos%2===0)this.noiseBurst(.07,.022,pos%4===0?170:860);if(pos%4===0)this.synth(72,.11,'square',.018,0,this.music,-22);}else if(this.scene==='surface'&&(pos===3||pos===11))this.insectChirp();else if(this.scene==='nest'&&pos===10)this.noiseBurst(.18,.008,260);this.step++;}
    tone(freq=240,duration=.08,type='sine',gain=.08,slide=0){const x=this.ensure();if(!x||this.muted)return;this.synth(freq,duration,type,gain,0,this.fx,slide);}
    ui(){this.tone(260,.06,'triangle',.035,45);}
    command(kind='move'){const v={attack:[120,.14,'sawtooth',.09,110],gather:[330,.12,'triangle',.06,90],build:[180,.13,'square',.045,-45],move:[240,.08,'triangle',.045,35]}[kind]||[240,.08,'triangle',.04,30];this.tone(...v);}
    event(text=''){const now=performance.now(),kind=/攻擊|交戰|傷亡|陣亡|威脅/.test(text)?'danger':/羽化|形成|完成|勝利/.test(text)?'rise':'notice';if(now-(this.last[kind]||0)<1100)return;this.last[kind]=now;if(kind==='danger'){this.tone(82,.3,'sawtooth',.11,-34);setTimeout(()=>this.tone(68,.35,'square',.055,-18),90);}else if(kind==='rise'){this.tone(220,.24,'triangle',.06,220);setTimeout(()=>this.tone(330,.3,'sine',.05,260),120);}else this.tone(190,.16,'sine',.05,70);}
  }
  root.AntAudio=AntAudio;
})(window);
