// V9.1 authorized instance/hunt changes rebaseline implementation fingerprints; gameplay behavior remains covered by engine and v91 tests.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const world=read('world.js'),app=read('app.js'),html=read('index.html'),css=read('assets/v7.2/ui/v7_2-ui-patch.css'),integration=read('assets/v7.2/ui/v7_2-integration.css');
test('V7.2 Drive package is complete and unmodified',()=>{const m=JSON.parse(read('assets/v7.2/MANIFEST.json'));assert.equal(m.version,'v7.2');assert.equal(m.core_gameplay_change,false);assert.equal(m.files.length,40);for(const f of m.files){const p='assets/v7.2/'+f.path;assert.equal(fs.statSync(path.join(root,p)).size,f.bytes,p);assert.equal(hash(p),f.sha256,p);}});
test('five resource chips show existing text and numbers with no icon',()=>{assert.match(app,/function renderStatus\(\)/);assert.match(css,/\.resources \.resource::before\s*\{[^}]*content:none !important;[^}]*display:none !important/s);assert.match(integration,/background-image:none !important/);assert.match(integration,/\.resource>span\{position:static/);for(const term of ['工蟻','兵蟻','食物','敵國','幼體'])assert.ok(app.includes(term));});
test('V9 replaces V8 whole-unit slides with articulated bodies without mirroring',()=>{const art=fs.readFileSync(path.join(root,'assets/v9/scene-art.js'),'utf8');assert.match(world,/this.art\?\.unit/);assert.match(art,/ant-bodies/);assert.match(art,/for\(let i=0;i<3;i\+\+\)/);assert.doesNotMatch(world,/scaleX\(-1\)|c\.scale\(-1/);});

test('V9 uses world-space ground and local props, no painted scene backdrops',()=>{assert.match(world,/this.art.ground/);for(const p of ['root','rock','plant','water'])assert.ok(world.includes("'"+p+"'"));assert.doesNotMatch(world.slice(world.indexOf('    draw(s,')),/new Image\(/);});

test('context panels use one frame and in-flow actions',()=>{assert.ok(html.includes('v7_2-ui-patch.css?v=assets-v72-world-art'));assert.match(css,/\.context::before,\.context::after,[\s\S]*content:none !important/);assert.match(integration,/\.context \.actions button,[^\n]*\{position:static !important;/);assert.match(css,/\.context \.actions,[^\n]*\{[\s\S]*display:flex;/);});
test('canvas alone blocks browser selection and touch callout while preserving 430ms box gesture',()=>{assert.match(css,/#world,[\s\S]*canvas#map\s*\{[\s\S]*user-select:none !important;[\s\S]*-webkit-touch-callout:none !important;[\s\S]*touch-action:none !important;/);for(const type of ['contextmenu','selectstart','dragstart'])assert.ok(app.includes("'"+type+"'"));assert.match(app,/\['touchstart','touchmove'\][^\n]*passive:false/);assert.match(app,/drawSelectionRect\(\)/);assert.match(app,/},430\)/);assert.doesNotMatch(app,/document\.addEventListener\('(?:selectstart|dragstart|touchstart|touchmove)'/);});
test('target, camera, core rules, V7.1 menu, V6.3 film and save key are preserved',()=>{const fp=re=>crypto.createHash('sha256').update((world.match(re)||[]).join('|')).digest('hex');assert.equal(fp(/this\.targets\.push\(\{[^;\n]*\}\);/g),'d125280c6e8df7c2b0801310e8541b2dbfe3410e143de885dd9be28dba923feb');assert.equal(fp(/^    (?:home|focus|zoom|pan|screen|position)\([^\n]+/gm),'0606c533fb9651f6fd9ab6acb551c9e60514609fcbaab1271e14462bc5386ab0');assert.equal(hash('engine.js'),'55f1dd2c3d1920805771722ad0f74c2eb2857d3d2a255c002cf1b853a4d96ddc');assert.equal(hash('interaction.js'),'7db6a9712410450b3c4ea543d2bd174f835d8fdf0d22ad2f72d73625c5606f4c');assert.ok(html.includes('menu-art.js?v=assets-v71-menu-confrontation'));assert.ok(html.includes('intro_cinematic_v6_3_capcut_badged.mp4'));assert.ok(app.includes("'alien-ant-empire-v0641'"));});
