const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../engine'),C=require('../interaction'),R=require('../release-rules');
function quiet(seed=91971){const s=E.create(seed);s.food=5000;s.queenRate=0;for(const n of s.colonies)n.attackDelay=99999;return s;}
function step(s,seconds){for(let i=0;i<seconds*4&&!s.ended;i++)E.tick(s,.25)}
test('outposts have distinct rows, near/far tiers and real portal-only links for ten seeds',()=>{for(let seed=1;seed<=10;seed++){const s=quiet(seed),entries=s.colonies.map(n=>E.xy(n.zones.entry));assert.equal(new Set(entries.map(e=>e.y)).size,4);const distances=s.colonies.map(n=>E.distance(E.xy(s.mainExit),E.xy(n.zones.entry)));assert.ok(Math.max(...distances)-Math.min(...distances)>12);for(const n of s.colonies){const path=E.path(s,E.HOME,n.queenK);assert.ok(path.includes(n.zones.entry));assert.ok(path.includes(n.entryK));assert.equal(E.cell(s,n.zones.entry).outpost,n.id);}}});
test('targets scale periodically, have hard caps and do not spawn on entry',()=>{const s=quiet(),base=E.workers(s)[0];for(let i=0;i<51;i++)s.ants.push({...structuredClone(base),id:s.nextId++});const before=s.ants.length;R.reviewGrowth(s,E);assert.equal(s.playerActivePopulation,60);assert.equal(s.ants.length,before);for(const n of s.colonies){assert.ok(n.targetPopulation<=n.populationCap);assert.ok(n.targetPopulation>=35)}const goals=s.colonies.map(n=>n.targetPopulation);s.ants=s.ants.filter(a=>a.faction==='enemy'||a.id===base.id);s.time+=20;R.reviewGrowth(s,E);assert.deepEqual(s.colonies.map(n=>n.targetPopulation),goals);});
test('functional nest destruction affects growth and military/special caste production',()=>{const s=quiet(),n=s.colonies[0];assert.equal(R.growthRate(n),1);n.disabledRooms=['nursery','store'];assert.ok(R.growthRate(n)<.11);n.disabledRooms.push('military');assert.equal(R.birthJob(s,n,[]),'forage');});
for(const role of ['near','hunter','armored','deep_forest'])test('postwar '+role+' returns through portals with reload, no teleport',()=>{let s=quiet(),n=s.colonies.find(n=>n.role===role),a=E.workers(s)[0];s.ants=s.ants.filter(a=>a.faction==='player');s.wildlife=[];a.k=n.queenK;Object.assign(a,E.xy(a.k));E.clearWork(a);n.fallen=true;n.queen=0;n.collapseAt=s.time;R.postWar(s,E);assert.ok(a.returnHome);assert.equal(a.k,n.queenK);E.tick(s,.25);assert.equal(E.nestId(a.k),n.id);s=E.restore(E.serialize(s));a=s.ants.find(w=>w.id===a.id);const visited=new Set();for(let i=0;i<2000&&a.returnHome;i++){E.tick(s,.25);visited.add(a.k)}assert.ok(visited.has(n.entryK));assert.ok(visited.has(n.zones.entry));assert.ok(visited.has(s.mainExit));assert.equal(E.nestId(a.k),null);assert.equal(E.isSurface(s,a.k),false);assert.equal(a.returnHome,undefined);});
test('loot and later manual orders take priority over postwar return',()=>{const s=quiet(),n=s.colonies[0],a=E.workers(s)[0];a.k=n.queenK;Object.assign(a,E.xy(a.k));a.carry=4;n.fallen=true;n.queen=0;n.clearedOrderSerial=0;R.postWar(s,E);assert.equal(a.returnHome,undefined);assert.equal(a.carry,4);a.carry=0;const k=E.neighbors(s,a.k)[0];E.cell(s,k).seen=true;C.order(s,[a.id],k);R.postWar(s,E);assert.equal(a.returnHome,undefined);assert.ok(a.group);});
test('entry order automatically explores and discovers targets; manual move cancels automation',()=>{const s=quiet(),n=s.colonies.find(n=>n.role==='near'),a=E.workers(s)[0];s.ants=[a];s.wildlife=[];a.caste='soldier';a.k=n.zones.entry;Object.assign(a,E.xy(a.k));E.cell(s,a.k).seen=true;C.direct(s,[a.id],{kind:'enemyNest',k:a.k,colony:n.id},a.k);const before=s.cells.filter(c=>c.nestId===n.id&&c.seen).length;step(s,12);assert.equal(E.nestId(a.k),n.id);assert.ok(s.cells.filter(c=>c.nestId===n.id&&c.seen).length>before+4);const g=s.groups.find(g=>g.id===a.group);assert.ok(g.autoAssault);const target=E.neighbors(s,a.k)[0];C.order(s,[a.id],target);assert.equal(s.groups.find(g=>g.id===a.group).autoAssault,undefined);});
for(const type of ['seed','fungi'])test(type+' regenerates below minimum after cooldown, never on blocked terrain',()=>{const s=quiet();s.resources=[];s.wildlife=[];s.ants=[];s.time=R.COOLDOWNS[type]-1;R.ecology(s,E);assert.ok(!s.resources.some(r=>r.type===type));s.time=500;R.ecology(s,E);const r=s.resources.find(r=>r.type===type);assert.ok(r);const c=E.cell(s,r.k);assert.ok(c.open&&!c.sealed);assert.ok(!['water','rock','log'].includes(c.terrain));assert.ok(!s.colonies.some(n=>E.distance(c,E.xy(n.zones.entry))<2));});
test('wildlife uses separate slower large cooldown, new IDs and bounded populations',()=>{const s=quiet();s.resources=[];s.wildlife=[];s.ants=[];s.time=300;R.ecology(s,E);assert.ok(s.wildlife.some(w=>w.sizeClass==='small'));assert.ok(!s.wildlife.some(w=>w.sizeClass==='large'));const ids=s.wildlife.map(w=>w.id);for(const w of s.wildlife)w.dead=true;s.time=900;R.ecology(s,E);assert.ok(s.wildlife.some(w=>w.sizeClass==='large'));assert.ok(s.wildlife.every(w=>!ids.includes(w.id)));for(let i=0;i<30;i++){s.time+=800;R.ecology(s,E)}assert.ok(s.wildlife.length<=R.ECO.maxWildlife);assert.ok(s.resources.length<=R.ECO.maxSources);assert.ok(s.resources.reduce((n,r)=>n+r.amount,0)<=R.ECO.maximum);});
test('ecology and growth serialize without instant replenishment on reload',()=>{const s=quiet();s.resources=[];s.time=500;R.ecology(s,E);const restored=E.restore(E.serialize(s));assert.deepEqual(restored.ecosystem,s.ecosystem);const count=restored.resources.length;R.ecology(restored,E);assert.equal(restored.resources.length,count);assert.deepEqual(restored.colonies.map(n=>n.targetPopulation),s.colonies.map(n=>n.targetPopulation));});
test('sixty-minute depleted-forest ecology keeps recoverable food with bounded object count',()=>{const s=quiet();s.ants=[];s.resources=[];s.wildlife=[];let harvest=0;for(let t=30;t<=3600;t+=30){s.time=t;R.ecology(s,E);if(t%180===0){harvest+=s.resources.reduce((n,r)=>n+r.amount,0);s.resources.forEach(r=>{r.amount=0;r.depletedAt=t});if(s.wildlife[0])s.wildlife[0].dead=true;}assert.ok(s.resources.length<=R.ECO.maxSources);assert.ok(s.wildlife.length<=R.ECO.maxWildlife)}s.time+=150;R.ecology(s,E);assert.ok(harvest>1000);assert.ok(s.resources.some(r=>r.amount>0));assert.ok(s.wildlife.some(w=>!w.dead));});
test('single gameplay BGM loops at low gain, survives views and mute without restarting',async()=>{const fs=require('fs'),vm=require('vm'),created=[],source={};class Audio{constructor(){this.paused=true;this.currentTime=0;this.dataset={}}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}}const win={AntAssets:{manifest:{},ready:Promise.resolve(),audio:key=>key==='bgmNest'?source:null,cloneAudio:key=>{const a=new Audio();a.dataset.assetKey=key;created.push(a);return a}},addEventListener(){},removeEventListener(){}};vm.runInNewContext(fs.readFileSync(require('path').join(__dirname,'../audio.js'),'utf8'),{window:win,Audio,document:{hidden:false,addEventListener(){},removeEventListener(){}},localStorage:{getItem(){return null},setItem(){}},performance:{now:()=>1000},setTimeout:()=>1,clearTimeout(){}});const audio=new win.AntAudio();audio.startGameplay();await Promise.resolve();const track=audio.externalBgm;assert.equal(track.loop,true);assert.equal(track.volume,.24);track.currentTime=12;audio.setScene('surface');audio.setScene('combat');audio.setMuted(true);assert.equal(track.muted,true);audio.setMuted(false);await Promise.resolve();assert.equal(audio.externalBgm,track);assert.equal(track.currentTime,12);assert.equal(created.length,1);audio.destroy();});

test('a guarded underground portal permits transition before same-layer combat',()=>{const s=quiet(),n=s.colonies.find(n=>n.role==='hunter'),a=E.workers(s)[0],enemy=s.ants.find(a=>a.faction==='enemy'&&a.colony===n.id);s.ants=[a,enemy];a.caste='soldier';a.hp=a.maxHp=200;a.k=n.zones.entry;Object.assign(a,E.xy(a.k));enemy.k=n.entryK;Object.assign(enemy,E.xy(enemy.k));enemy.job='guard';E.cell(s,a.k).seen=true;C.direct(s,[a.id],{kind:'enemyNest',k:a.k,colony:n.id},a.k);step(s,1);assert.equal(E.nestId(a.k),n.id);assert.ok(a.layerTransitions.length>=1);});

test('a new explicit worker guard order is not reclaimed by postwar automation',()=>{const s=quiet(),n=s.colonies[0],a=E.laborers(s)[0];a.k=n.entryK;Object.assign(a,E.xy(a.k));n.fallen=true;n.queen=0;n.clearedOrderSerial=0;R.postWar(s,E);assert.ok(a.returnHome);C.assignSelected(s,[a.id],'guard',a.k);R.postWar(s,E);assert.equal(a.returnHome,undefined);assert.equal(a.job,'guard');assert.equal(a.guardTarget,a.k);});
