const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../engine.js'),C=require('../interaction.js');
test('four instanced nests connect only via their surface portal',()=>{for(const seed of [1,2,3,44,77,123,892,1283,19191,39919]){const s=E.create(seed);assert.equal(s.enemyNests.length,4);for(const n of s.enemyNests){const path=E.path(s,E.HOME,n.queenK);assert.ok(path);assert.ok(path.includes(n.entry));assert.ok(path.includes(n.entryK));assert.ok(n.rooms.length>=5);assert.ok(E.neighbors(s,n.entry).includes(n.entryK));assert.ok(E.neighbors(s,n.entryK).includes(n.entry));const reached=new Set([n.queenK]),q=[n.queenK];for(let i=0;i<q.length;i++)for(const k of E.neighbors(s,q[i]))if(!E.isSurface(s,k)&&!reached.has(k)){reached.add(k);q.push(k)}assert.ok([...reached].every(k=>E.nestId(k)===n.id));assert.ok(!reached.has(E.HOME));}}});
test('instance restore is idempotent and preserves active cargo',()=>{let s=E.create(8191);const n=s.enemyNests[1],a=E.workers(s)[0];a.k=n.queenK;Object.assign(a,E.xy(a.k));a.carry=4.5;a.cargoTask=983;a.haulTask={targetK:n.queenK,corpseId:93,nestId:n.id};const length=s.cells.length;s=E.restore(E.serialize(s));assert.equal(s.cells.length,length);assert.equal(s.enemyNests.length,4);assert.equal(s.ants.find(w=>w.id===a.id).carry,4.5);assert.equal(s.ants.find(w=>w.id===a.id).haulTask.targetK,n.queenK);assert.ok(E.path(s,n.queenK,E.HOME).length>0);});
test('different maps never see or attack at identical coordinates',()=>{const s=E.create(8192),a=E.workers(s)[0],b=s.ants.find(a=>a.faction==='enemy'),k=s.enemyNests[1].queenK;const p=E.xy(k);a.k=E.key(p.x,p.y);Object.assign(a,p);b.k=k;Object.assign(b,p);assert.equal(E.sameMap(s,a.k,b.k),false);assert.equal(E.visible(s,a,b),false);});
test('three wildlife scales and dormant future flyer data exist without new player combat caste',()=>{const s=E.create(8193);assert.deepEqual(new Set(s.wildlife.map(w=>w.sizeClass)),new Set(['small','medium','large']));assert.equal(s.castePlans.flyer.enabled,false);assert.equal(s.castePlans.flyer.source,'nursery');assert.ok(!E.workers(s).some(w=>w.soldierType==='flyer'));});
test('selected ants can target an enemy facility without being substituted',()=>{const s=E.create(8194),room=s.enemyNests[1].rooms.find(r=>r.type==='military'),a=E.workers(s)[0];a.k=room.k;Object.assign(a,E.xy(a.k));a.caste='soldier';const result=C.direct(s,[a.id],{kind:'enemyRoom',id:room.id,k:room.k},room.k);assert.equal(result.count,1);assert.equal(s.groups.find(g=>g.id===a.group).enemyRoomId,room.id);});

test('V9 legacy active queen cargo migrates once without losing inventory or orders',()=>{const fs=require('fs'),zlib=require('zlib'),raw=zlib.gunzipSync(fs.readFileSync(require('path').join(__dirname,'fixtures/v9-legacy-cargo.json.gz'))).toString(),old=JSON.parse(raw),s=E.restore(raw),a=s.ants.find(a=>a.cargoTask===831),n=s.colonies.find(n=>n.role==='near');assert.equal(s.food,old.food);assert.equal(a.carry,4);assert.equal(E.nestId(a.k),n.id);assert.equal(s.routes.find(r=>r.id===831).k,n.queenK);assert.equal(a.haulTask.targetK,n.queenK);assert.ok(E.path(s,a.k,E.HOME));assert.equal(E.restore(E.serialize(s)).cells.length,s.cells.length);});
test('destroying enemy facilities damages their own economy and slows reinforcement',()=>{for(const type of ['military','nursery','store']){const s=E.create(91921),n=s.colonies[0],room=s.enemyNests.find(x=>x.id===n.id).rooms.find(r=>r.type===type),a=E.workers(s)[0];s.ants=s.ants.filter(a=>a.faction==='player');s.wildlife=[];n.birth=0;n.food=80;room.hp=.1;a.k=room.k;Object.assign(a,E.xy(a.k));a.caste='soldier';a.hp=a.maxHp=100;C.direct(s,[a.id],{kind:'enemyRoom',id:room.id,k:room.k},room.k);E.tick(s,.25);assert.equal(room.destroyed,true);assert.ok(n.disabledRooms.includes(type));if(type==='store')assert.ok(n.food<65);else assert.ok(n.birth<.25);}});
test('reusing selected soldiers replaces hunt/facility orders rather than retaining stale targets',()=>{const s=E.create(91922),a=E.workers(s)[0],w=s.wildlife.find(w=>w.sizeClass==='small');a.caste='soldier';a.k=w.k;Object.assign(a,E.xy(a.k));E.cell(s,w.k).seen=true;C.direct(s,[a.id],{kind:'wildlife',id:w.id,k:w.k},w.k);let g=s.groups.find(g=>g.id===a.group);assert.equal(g.wildlifeId,w.id);const target=E.neighbors(s,w.k)[0];E.cell(s,target).seen=true;C.direct(s,[a.id],{kind:'ground',k:target},target);g=s.groups.find(g=>g.id===a.group);assert.equal(g.wildlifeId,undefined);assert.equal(g.target,target);});
test('enemy explored chambers never increase player nursery space',()=>{const s=E.create(91923),before=E.pressure(s).space;for(const c of s.cells.filter(c=>c.nestId!==undefined))c.seen=true;assert.equal(E.pressure(s).space,before);});
